import {
  LayoutDashboard,
  Users,
  Settings,
  CheckSquare,
  MessageSquare,
  Bell,
  Package,
  CalendarDays,
  Megaphone,
  BarChart2,
  FileText,
  ClipboardList,
  Printer,
  Eye,
  EyeOff,
  AlertTriangle,
  Award,
  StickyNote,
  Pin,
  LogOut,
  LogIn,
  Plus,
  Pencil,
  Trash2,
  File,
  FileArchive,
  FileCheck2,
  FileX2,
  UserCheck,
  User,
  UsersRound,
  ScanLine,
  BadgeCheck,
  ClipboardCheck,
  ClipboardX,
  Clipboard,
  ClipboardEdit,
  ClipboardList as ClipboardListIcon,
} from 'lucide-react';

export const icons = {
  dashboard: LayoutDashboard,
  users: Users,
  settings: Settings,
  task: CheckSquare,
  message: MessageSquare,
  notification: Bell,
  package: Package,
  calendar: CalendarDays,
  announcement: Megaphone,
  report: BarChart2,
  document: FileText,
  audit: ClipboardList,
  print: Printer,
  eye: Eye,
  eyeOff: EyeOff,
  warning: AlertTriangle,
  award: Award,
  note: StickyNote,
  pin: Pin,
  logout: LogOut,
  login: LogIn,
  plus: Plus,
  edit: Pencil,
  delete: Trash2,
  file: File,
  archive: FileArchive,
  fileCheck: FileCheck2,
  fileX: FileX2,
  userCheck: UserCheck,
  user: User,
  usersRound: UsersRound,
  scan: ScanLine,
  badge: BadgeCheck,
  clipboardCheck: ClipboardCheck,
  clipboardX: ClipboardX,
  clipboard: Clipboard,
  clipboardEdit: ClipboardEdit,
  clipboardList: ClipboardListIcon,
};
